#!/bin/bash

GREEN='\033[0;32m'
NC='\033[0m' # No Color
#echo "${GREEN} $(mpc --host=$HOME/.local/share/mpd/socket current) ${NC}"
mpc --host=$HOME/.local/share/mpd/socket current


case $BLOCK_BUTTON in
  1) mpc --host=$HOME/.local/share/mpd/socket toggle
esac
